apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-snakeforged-dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: snakeforged
  - path: ingress.yaml
    target:
      kind: Ingress
      name: snakeforged

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: v1.0.0

labels:
  - pairs:
      environment: dev
    includeSelectors: false

replicas:
  - name: snakeforged
    count: 2
