-- Flyway Migration: V1__Initial_schema.sql
-- Initializes the H2 database schema for SnakeForged

-- DIFFICULTY_CONFIG table: stores difficulty levels with tick intervals
CREATE TABLE IF NOT EXISTS difficulty_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(16) NOT NULL UNIQUE,
    tick_interval_ms INT NOT NULL,
    label VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- HIGHSCORE_ENTRY table: stores leaderboard entries
CREATE TABLE IF NOT EXISTS highscore_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficulty_id BIGINT NOT NULL,
    nickname VARCHAR(20) NOT NULL,
    score INT NOT NULL,
    achieved_at TIMESTAMP NOT NULL,
    source_hash VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (difficulty_id) REFERENCES difficulty_config(id)
);

-- Index for efficient leaderboard retrieval (top 10 per difficulty)
CREATE INDEX idx_highscore_difficulty_score ON highscore_entry(difficulty_id, score DESC, created_at ASC);

-- AUDIT_EVENT table: immutable audit log for highscore mutations
CREATE TABLE IF NOT EXISTS audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    highscore_id BIGINT,
    event_type VARCHAR(50) NOT NULL,
    actor_hash VARCHAR(64),
    difficulty_code VARCHAR(16),
    submitted_score INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (highscore_id) REFERENCES highscore_entry(id)
);

-- Index for audit log queries
CREATE INDEX idx_audit_event_created ON audit_event(created_at DESC);

-- Pre-populate difficulty levels
INSERT INTO difficulty_config (code, tick_interval_ms, label, active)
VALUES
    ('EASY', 100, 'Easy - Slow Speed', TRUE),
    ('MEDIUM', 70, 'Medium - Moderate Speed', TRUE),
    ('HARD', 40, 'Hard - Fast Speed', TRUE);
