-- Flyway Migration V1: initial schema for SnakeForged persistence layer

CREATE TABLE highscore_entry (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname    VARCHAR(20) NOT NULL,
    score       INT         NOT NULL,
    difficulty  VARCHAR(10) NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Efficient top-10 queries per difficulty level
CREATE INDEX idx_highscore_difficulty_score ON highscore_entry (difficulty, score DESC);

CREATE TABLE audit_event (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type     VARCHAR(50) NOT NULL,
    client_ip_hash VARCHAR(64),
    nickname       VARCHAR(20),
    score          INT,
    difficulty     VARCHAR(10),
    created_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
